# Generated by Django 2.2 on 2019-07-28 01:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='website.order_item'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(default=datetime.datetime(2019, 7, 28, 1, 35, 33, 131001, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='website.shop_item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='title',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_item',
            name='desc',
            field=models.CharField(default='timezone.now()', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_item',
            name='price',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_item',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 7, 28, 1, 56, 14, 637575, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='website.CustomUser')),
            ],
            options={
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
