# Generated by Django 2.2 on 2019-08-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_item_order_orderitem_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Product'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
