# Generated by Django 2.2 on 2019-07-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190728_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_item',
            name='price',
        ),
    ]
